name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Gradle Android
      uses: Raul6469/android-gradle-action@1.0.0
    - name: setup-android
      uses: msfjarvis/setup-android@0.2
